permissions:
  contents: write
name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIR: .
      FILE: cv
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile CV
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.FILE }}.tex  # Ensure the file extension is included
          working_directory: ${{ env.DIR }}

      - name: List files for debugging (before moving)
        run: ls -R ${{ env.DIR }}

      - name: Move PDF to Artifacts Directory
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/

      - name: List files in artifacts directory for debugging
        run: ls -R ./github_artifacts

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cv-pdf
          path: ./github_artifacts/${{ env.FILE }}.pdf

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: cv-pdf
          path: github_artifacts

      - name: List downloaded artifacts for debugging
        run: ls -R github_artifacts

      - name: Prepare Deploy Directory
        run: mkdir -p github_deploy && mv github_artifacts/${{ env.FILE }}.pdf github_deploy/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
          enable_jekyll: true

  copy-index-to-build:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Copy Index and CNAME to Branches
        uses: planetoftheweb/copy-to-branches@v1.3
        env:
          key: main
          files: index.html CNAME
